# Generated by Django 4.0.5 on 2022-06-07 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20220518_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='hotel_place',
            field=models.CharField(default='lucknow', max_length=50),
        ),
    ]
